# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "nodejs" do |nodejs|
    nodejs.vm.box = "precise64"
    nodejs.vm.box_url = "http://files.vagrantup.com/precise64.box"
    
    
    nodejs.vm.network :private_network, ip: "10.0.0.206"
    nodejs.ssh.forward_agent = true
    
    nodejs.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "angular.dev"]
    end

    
    
    #config.ssh.forward_agent = true
    
    #nodejs.vm.forward_port 8000, 4567
    #nodejs.vm.host_name = "angularjs.dev"
    
    nfs_setting = RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/
    config.vm.synced_folder "./../", "/var/www/angular", id: "vagrant-root" , :nfs => nfs_setting
    
    nodejs.vm.provision :shell, :path => "provision.sh"
  end

end
